version: "3.7"
services:
  backuper:
    image: kchlistala89/aureox-backuper:0.0.7
    volumes:
      - ${APP_DATA_DIR}/configs:/configs
      - ${APP_DATA_DIR}/backups:/backups
      - ${APP_DATA_DIR}/../immich/data/upload:/immich

  proxy:
    image: caddy:alpine
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 12002:12002
